import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile_pic.jpg" />
      </Head>
      <h1 className="bg-red-500">
        This is a facebook clone by Saniru Rajapaksha 😎😎
      </h1>
    </div>
  );
}
